/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
//import javax.swing.Icon;
import javax.swing.ImageIcon;

        

/**
 *
 * @author laboratorio
 */
public class Principal extends javax.swing.JFrame {
    
    
    private int numeroImagen =1;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ajustarImagen(new javax.swing.ImageIcon(getClass().
                getResource("/recursos/Colinasazules.jpg")));
//panelSlider.add(new Slider());
        
    }

    private void ajustarImagen(javax.swing.ImageIcon imageIco){
       Image img=imageIco.getImage();
       //img.getScaledInstance(
       
       labelimagen.setIcon(
               new ImageIcon(
               img.getScaledInstance(
               labelimagen.getWidth(),
               labelimagen.getHeight(),
               Image.SCALE_DEFAULT)
        
       )
       );
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarArchivo = new javax.swing.JFileChooser();
        panelSlider = new javax.swing.JPanel();
        labelimagen = new javax.swing.JLabel();
        buttonSiguiente = new javax.swing.JButton();
        buttonAtras = new javax.swing.JButton();
        prueba = new javax.swing.JLabel();
        buttonCargarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Colinasazules.jpg"))); // NOI18N

        buttonSiguiente.setText(">");
        buttonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSiguienteMouseClicked(evt);
            }
        });
        buttonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiguienteActionPerformed(evt);
            }
        });

        buttonAtras.setText("<");
        buttonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAtrasMouseClicked(evt);
            }
        });
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });

        buttonCargarImagen.setText("Cargar Imagen");
        buttonCargarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCargarImagenMouseClicked(evt);
            }
        });
        buttonCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSliderLayout = new javax.swing.GroupLayout(panelSlider);
        panelSlider.setLayout(panelSliderLayout);
        panelSliderLayout.setHorizontalGroup(
            panelSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSliderLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(buttonAtras)
                .addGap(67, 67, 67)
                .addComponent(buttonSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSliderLayout.createSequentialGroup()
                .addComponent(labelimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(buttonCargarImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSliderLayout.setVerticalGroup(
            panelSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSliderLayout.createSequentialGroup()
                .addGroup(panelSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSliderLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSliderLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSliderLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(buttonCargarImagen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAtras)
                    .addComponent(buttonSiguiente))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSiguienteActionPerformed

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void buttonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAtrasMouseClicked
        ajustarImagen(new javax.swing.ImageIcon(getClass().
                getResource("/recursos/"+getPreviousImagen())));
        

//labelimagen.setIcon(new javax.swing.ImageIcon(getClass().
  //      getResource("/recursos/"+getPreviousImagen())));
// TODO add your handling code here:
    }//GEN-LAST:event_buttonAtrasMouseClicked

    private void buttonSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSiguienteMouseClicked
ajustarImagen(new javax.swing.ImageIcon(getClass().
                getResource("/recursos/"+getNextImagen())));
        
// TODO add your handling code here:
    }//GEN-LAST:event_buttonSiguienteMouseClicked

    private void buttonCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCargarImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCargarImagenActionPerformed

    private void buttonCargarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCargarImagenMouseClicked
        try {
            seleccionarArchivo.showOpenDialog(null);
            File f=seleccionarArchivo.getSelectedFile();
            ajustarImagen(new ImageIcon(ImageIO.read(f)));
            
// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCargarImagenMouseClicked

    private String getNextImagen(){
        switch(numeroImagen){
            case 1:
                numeroImagen=2;
                return "Invierno.jpg";
            case 2:
                numeroImagen=3;
                return "Puestadesol.jpg";
            case 3:
                numeroImagen=1;
                return "Colinasazules.jpg";
            default:
                throw new AssertionError();
       }
        
    }
    
    
    private String getPreviousImagen(){
        switch(numeroImagen){
            case 1:
                numeroImagen=3;
                return "Colinasazules.jpg";
            case 2:
                numeroImagen=1;
                return "Puestadesol.jpg";
            case 3:
                numeroImagen=2;
                return "Invierno.jpg";
            default:
                throw new AssertionError();
       }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtras;
    private javax.swing.JButton buttonCargarImagen;
    private javax.swing.JButton buttonSiguiente;
    private javax.swing.JLabel labelimagen;
    private javax.swing.JPanel panelSlider;
    private javax.swing.JLabel prueba;
    private javax.swing.JFileChooser seleccionarArchivo;
    // End of variables declaration//GEN-END:variables
}
